# Dockerfile.openapi
FROM nginx:alpine

# Copy the OpenAPI spec into the correct location for serving
COPY docs/openapi.yaml /usr/share/nginx/html/openapi.yaml

# Copy the NGINX configuration file
COPY .k8/nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to serve the OpenAPI documentation
EXPOSE 80
