apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"openapi-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"openapi-server"}},"template":{"metadata":{"labels":{"app":"openapi-server"}},"spec":{"containers":[{"image":"gcr.io/gothic-oven-433521-e1/openapi-server:latest","name":"openapi-server","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2024-09-02T21:13:26Z"
  generation: 8
  name: openapi-deployment
  namespace: default
  resourceVersion: "6277737"
  uid: a0f7ffd5-2728-4561-a15c-94e105572b40
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-09-02T16:27:20-06:00"
      creationTimestamp: null
      labels:
        app: openapi
    spec:
      containers:
      - image: gcr.io/gothic-oven-433521-e1/openapi-server:latest
        imagePullPolicy: Always
        name: openapi-server
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-09-02T22:37:08Z"
    lastUpdateTime: "2024-09-02T22:37:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-09-02T21:47:03Z"
    lastUpdateTime: "2024-09-02T22:38:19Z"
    message: ReplicaSet "openapi-deployment-b46c8995" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
