steps:
  # Step 1: Build the Docker image, using secret for build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/midi-file-server', '.']
    secretEnv: ['MY_SECRET_ENV']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/midi-file-server']

  # Step 3: Deploy to Kubernetes using the .k8 folder YAML configurations
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './.k8/midi-file-server-deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'  # Replace with your zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=midi-cluster'  # Replace with your cluster name

  # Optionally, apply MongoDB configs in the .k8 folder
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './.k8/mongodb-deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=midi-cluster'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/my-env-secret/versions/latest
      env: 'MY_SECRET_ENV'

images:
  - 'gcr.io/$PROJECT_ID/midi-file-server'

# enable with: gcloud services enable cloudbuild.googleapis.com
# trigger build: gcloud builds submit --config cloudbuild.yaml .