options:
  logging: CLOUD_LOGGING_ONLY  # or NONE if you want no logging

steps:
  # Step 1: Build the Docker image with the unique tag (commit SHA)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/midi-file-server:$SHORT_SHA', '.']
    secretEnv: ['MY_SECRET_ENV']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/midi-file-server:$SHORT_SHA']

  # Step 3: Replace the image tag in the deployment YAML file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's|image: gcr.io/.*/midi-file-server:.*|image: gcr.io/$PROJECT_ID/midi-file-server:$SHORT_SHA|' ./.k8/midi-file-server-deployment.yaml

  # Step 4: Deploy to Kubernetes using the updated YAML configurations
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './.k8/midi-file-server-deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=midi-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './.k8/midi-file-server-service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=midi-cluster'

  # MongoDB configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './.k8/mongodb-deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=midi-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './.k8/mongodb-service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=midi-cluster'

  # MongoDB persistent volume configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './.k8/mongodb-pv.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=midi-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './.k8/mongodb-pvc.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=midi-cluster'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/my-env-secret/versions/latest
      env: 'MY_SECRET_ENV'

images:
  - 'gcr.io/$PROJECT_ID/midi-file-server:$SHORT_SHA'

substitutions:
  _SHORT_SHA: "$SHORT_SHA
