apiVersion: apps/v1
kind: Deployment
metadata:
  name: midi-file-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: midi-file-server
  template:
    metadata:
      labels:
        app: midi-file-server
    spec:
      serviceAccountName: midi-server-admin
      containers:
      - name: midi-file-server
        image: gcr.io/gothic-oven-433521-e1/midi-file-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: LAST_BUILD_INFO
          value: "gcr.io/gothic-oven-433521-e1/midi-file-server:latest" 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/signer/signer.json
        volumeMounts:
        - name: gcr-secret
          mountPath: /var/secrets/gcr
          readOnly: true
        - name: signer-secret
          mountPath: /var/secrets/signer
          readOnly: true
      volumes:
      - name: gcr-secret
        secret:
          secretName: gcr-secret
      - name: signer-secret
        secret:
          secretName: signer-secret
autoscaling:
  horizontal:
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 180
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80