apiVersion: v1
kind: Service
metadata:
  name: openapi-service
  labels:
    app: openapi
spec:
  selector:
    app: openapi
  ports:
    - protocol: TCP
      port: 80        # Port on the service
      targetPort: 80  # Port on the container
  type: LoadBalancer