name: Makefile lint

on:
  push:
    branches:
      - '**' 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.1  # Try using an earlier, stable version

      - name: Install golangci-lint
        run: |
            wget https://github.com/golangci/golangci-lint/releases/download/v1.52.2/golangci-lint-1.60.3-linux-amd64.tar.gz
            tar xzf golangci-lint-1.60.3-linux-amd64.tar.gz
            sudo cp golangci-lint-1.60.3-linux-amd64/golangci-lint /usr/local/bin/
      - name: Run Makefile lint
        run: make lint
