name: Makefile lint

on:
  push:
    branches:
      - '**' 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.0  

      - name: Install golangci-lint
        run: |
          wget https://github.com/golangci/golangci-lint/releases/download/v1.56.2/golangci-lint-1.56.2-linux-amd64.tar.gz
          tar xzf golangci-lint-1.56.2-linux-amd64.tar.gz
          sudo cp golangci-lint-1.56.2-linux-amd64/golangci-lint /usr/local/bin/

      - name: Run Makefile lint
        run: make lint
