name: Go CI

on: [push]

jobs:
  golang-unit-tests:
    name: Run Golang Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0"

      - name: Run unit tests
        run: make test
